[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.26"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
ignored_error_codes = ["unreachable", "license", "code-size"]
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.ci_doc_gen]
src = 'test'
libs = ['lib']

[profile.gas]
test = 'test/gas'
match_test = 'test_Gas_**'

[profile.coverage]
no_match_path = "./test/invariants/*"

[fmt]
line_length = 100
tab_width = 2
multiline_func_header = 'params_first'
quote_style = 'double'
wrap_comments = true
ignore = ['lib']
# https://book.getfoundry.sh/reference/config/formatter

[invariant]
fail_on_revert = true

[profile.merkle_verification]
block_gas_limit = 1000000000000